test

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,3 +1,10 @@
 #!/bin/sh
 
+# Fail fast and fail hard.
+set -eo pipefail
+
 echo "source /app/.heroku/python/bin/virtualenvwrapper.sh" >> ~/.bashrc
+
+source ~/.bashrc
+
+mkvirtualenv kaleido_admin -p python3
